# XXX this conf needs settings for "Source is cachable" and "Source is elaborate".
# Both cs_YouTube and cs_GoogleCalendar are cachable.

configuration = {
    'cs_Agroeco_sci_quick_check': {
        'id': 'cs_agroeco_sci_quick_check',
        'dirname': 'cs_Agroeco_sci_quick_check',
        'title': 'Agroecosystem science qualifications',
        'render_id': 'quick_check',
        'desc': None,
        'form': 'parameters.xml',
        'script_id': None,
        'script_body': None,
        'file_id': None,
        'file_body': None,
        'template_id': 'quick_check',
        'template_body': 'quick_check.pt',
        'history': 'HISTORY.txt',
        'license': 'LICENSE.txt',
        'readme': 'README.txt',
        'version': 'version.txt',
    },
    'cs_Agroeco_food_sci_bachelor': {
        'id': 'cs_agroeco_food_sci_bachelor',
        'dirname': 'cs_Agroeco_food_sci_bachelor',
        'title': 'Agroecosystem science and food bachelor',
        'render_id': 'agroeco_food_bachelor',
        'desc': None,
        'form': 'parameters.xml',
        'script_id': None,
        'script_body': None,
        'file_id': None,
        'file_body': None,
        'template_id': 'agroeco_food_bachelor',
        'template_body': 'agroeco_food_bachelor.pt',
        'history': 'HISTORY.txt',
        'license': 'LICENSE.txt',
        'readme': 'README.txt',
        'version': 'version.txt',
    },
    'cs_AffinityTest': {
        'id': 'cs_affinity_test',
        'dirname': 'cs_AffinityTest',
        'title': 'Affinity test',
        'render_id': 'affinity_test',
        'desc': None,
        'form': 'parameters.xml',
        'script_id': 'counter',
        'script_body': 'counter.py',
        'file_id': None,
        'file_body': None,
        'template_id': 'affinity_test',
        'template_body': 'affinity_test.pt',
        'history': 'HISTORY.txt',
        'license': 'LICENSE.txt',
        'readme': 'README.txt',
        'version': 'version.txt',
    },
}
